cmake_minimum_required(VERSION 3.14)
project(Luapp_ARchive)
add_subdirectory(${CMAKE_SOURCE_DIR}/deps)
set(SOURCE_DIR ${CMAKE_SOURCE_DIR}/src)
set(HEADER_DIR ${CMAKE_SOURCE_DIR}/include)
set(SOURCE_FILES ${SOURCE_DIR}/main.cpp ${SOURCE_DIR}/LarMgr.cpp ${SOURCE_DIR}/lAssets.cpp ${SOURCE_DIR}/lSearcher.cpp ${SOURCE_DIR}/lloadentry.cpp ${SOURCE_DIR}/compiler.cpp)
set(HEADER_FILES ${HEADER_DIR}/lar.hpp ${HEADER_DIR}/LarMgr.hpp ${HEADER_DIR}/lAssets.hpp ${HEADER_DIR}/lSearcher.hpp ${HEADER_DIR}/lloadentry.hpp ${HEADER_DIR}/compiler.hpp)
add_executable(Luapp_ARchive ${SOURCE_FILES} ${HEADER_FILES})
target_link_libraries(Luapp_ARchive PRIVATE Lar_Deps)
target_include_directories(Luapp_ARchive PUBLIC ${HEADER_DIR})
target_precompile_headers(Luapp_ARchive PRIVATE ${HEADER_DIR}/lar.hpp)
target_compile_features(Luapp_ARchive PRIVATE cxx_std_17)
set_target_properties(Luapp_ARchive PROPERTIES OUTPUT_NAME "lar")
if(WIN32) 
    add_executable(wLuapp_ARchive ${SOURCE_DIR}/wmain.cpp ${SOURCE_FILES} ${HEADER_FILES})
    target_link_libraries(wLuapp_ARchive PRIVATE Lar_Deps)
    target_include_directories(wLuapp_ARchive PUBLIC ${HEADER_DIR})
    target_precompile_headers(wLuapp_ARchive PRIVATE ${HEADER_DIR}/lar.hpp)
    target_compile_features(wLuapp_ARchive PRIVATE cxx_std_17)
    set_target_properties(wLuapp_ARchive PROPERTIES OUTPUT_NAME "wlar" 
        WIN32_EXECUTABLE TRUE
    )
endif()